#!/bin/sh

#
echo · set init
cat << EOF > /t/init
{
	"env" : null,
	"path": "/bin/ls",
	"args": ["/"]
}
EOF

#
echo · get init
cat /t/init

#
echo · start
echo start > /t/start

#
echo · open-close stdin
echo >> /t/stdin
